### ISSUE TITLE
Canvas fade-out gradient looks out of place

### ISSUE THREAD

**Issue by soyeonswife63** [SpotX-Official/SpotX-Bash#56] opened 2024-08-08 10:35 UTC
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have read the FAQ
- [X] I have checked previous issues, open and closed
- [X] I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash

### Сountry of your account

Turkiye

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify version: Spotify for macOS (Intel) 1.2.43.420.gc7b23f70
- OS: macOS Sonoma 14.6
- Shell: zsh
```

### 📝 Description

1. Open Spotify, patched with SpotX's new theme
2. Play a song with Canvas present
3. Observe "Now playing view"

Expected behavior: Canvas is faded out nicely to a black background

Actual behavior: Since "Now playing view" has a colored background, the black fading out gradient at the bottom of the Canvas looks out of place

### 🖥️ Terminal Input/Output

I used `curl -sSL https://spotx-official.github.io/run.sh | bash -s -- -B -p`

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/7ef76d27-0eb3-46e5-ad23-d37b614747cf)
![image](https://github.com/user-attachments/assets/5b764f18-1c20-4032-8d25-cb2b70d190d5)

**Comment by jetfir3** [comment] 2024-08-08 13:31
SpotX-Bash is not altering any UI code... only turning official experimental features on/off. 

You have said "I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash". So when you enabled canvas on STOCK client it gives you your expected "Canvas is faded out nicely to a black background" behavior?

**Comment by soyeonswife63** [comment] 2024-08-10 17:33
> You have said "I have completed all troubleshooting steps and the issue is not present on stock but returns after re-applying SpotX-Bash".
> 
> So when you enabled canvas on STOCK client it gives you your expected "Canvas is faded out nicely to a black background" behavior?

I'm not sure if there's Canvas on stock? But I am simply comparing the patched ones between OS (macOS vs Windows)



Also, my Premium has expired, so I will edit the issue to say that I don't have Premium ^^;;
Anyway, trying to enable Developer Mode hasn't worked:
![image](https://github.com/user-attachments/assets/5bd2b268-29bd-4297-adf3-aab9c89d3c8e)
![image](https://github.com/user-attachments/assets/fb30b60a-45c0-4c3d-92c0-a9a0b091b069)

**Comment by jetfir3** [comment] 2024-08-10 19:25
> I'm not sure if there's Canvas on stock? But I am simply comparing the patched ones between OS (macOS vs Windows)

Can only compare macOS to macOS.. and must compare same exact build version too, as things can change version to version. 

> Also, my Premium has expired, so I will edit the issue to say that I don't have Premium

You were previously patching the client using the `-p` flag. This must be removed if you are not a paid premium user. You will also need to use `-f` to force SpotX-Bash to repatch.

> Anyway, trying to enable Developer Mode hasn't worked:
The top toolbar while the client is in focus should also show `Developer` where the Debug Window will appear in drop-down menu.

**Comment by amd64fox** [comment] 2024-08-10 19:40
Canvases are currently in the testing phase in the native client, so there are minor issues. The problem with the incorrect gradient can be resolved by disabling the background color based on the cover for the right sidebar


- activate developer mode as above
- `debug window`  => `remote config`
- find  `enableRightSidebarExtractedColorsExtract ` and select false

@jetfir3

**Comment by amd64fox** [comment] 2024-08-10 19:40
I don't use this experiment at all because it constantly breaks something in the layout. You shouldn't have enabled it for everyone

**Comment by jetfir3** [comment] 2024-08-10 20:19
> Canvases are currently in the testing phase in the native client, so there are minor issues. The problem with the incorrect gradient can be resolved by disabling the background color based on the cover for the right sidebar

> I don't use this exp at all because it constantly breaks something in the layout. 

At least with v1.2.43.x, it seems this UI issue can be resolved with a full uninstall (deleting app cache/data + app) then reinstalling. So some leftover data from previous build is causing issues.

So two fixes:
1. disabling `enableRightSidebarExtractedColorsExtract`
2. full uninstall (see uninstall steps in [Troubleshooting](https://github.com/SpotX-Official/SpotX-Bash/wiki/Troubleshooting)) + fresh install
- finding the exact file to delete would be ideal, avoiding the need to log in again.

**Closed** 2024-08-10 20:38 UTC
